package View;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author tomea
 */
import database_manager_interbase.ConexionIB;
import interbase.interclient.Connection;
import javax.swing.*;
import javax.swing.table.*;

import java.util.Vector;

import javax.swing.tree.TreePath;

public class createTV extends javax.swing.JFrame {

    Login log;
    private DefaultTableModel mdlCol;
    private JTextArea txtDDL;

    public createTV(Login log) {
        initComponents();
        this.log = log;
        setLocationRelativeTo(null);
        cmbTV.removeAllItems();
        cmbTV.addItem("Table");
        cmbTV.addItem("View");
        cmbTD.removeAllItems();
        cmbTD.addItem("VARCHAR");
        cmbTD.addItem("INTEGER");
        cmbTD.addItem("DECIMAL");
        cmbTD.addItem("DATE");
        cmbTD.addItem("BOOLEAN");
        cmbTV.setSelectedIndex(0);
        jLabel1.setText("Nombre de Tabla:");

        mdlCol = new DefaultTableModel(
                new Object[]{"Nombre", "Tipo de Dato", "Longitud", "NOT NULL", "PK"}, 0
        );

        tblTV = new JTable(mdlCol);
        TableColumn colTipo = tblTV.getColumnModel().getColumn(1);
        colTipo.setCellEditor(new DefaultCellEditor(cmbTD));
        tASelect.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                actualizarDDL();
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                actualizarDDL();
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                actualizarDDL();
            }
        });
        txtNombreTV.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                actualizarDDL();
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                actualizarDDL();
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                actualizarDDL();
            }
        });

    }

    private void actualizarDDL() {
        if(mdlCol == null){
            return;
        }
        String nombre = txtNombreTV.getText().trim();
        if (nombre.isEmpty()) {
            tAddl.setText("-- Escribe un nombre para continuar");
            return;
        }

        String tipo = (String) cmbTV.getSelectedItem();

        if ("Table".equalsIgnoreCase(tipo)) {
            StringBuilder ddl = new StringBuilder("CREATE TABLE " + nombre + " (\n");
            Vector<Vector> data = mdlCol.getDataVector();
            for (int i = 0; i < data.size(); i++) {
                Vector fila = mdlCol.getDataVector().get(i);
                String colNombre = fila.get(0).toString();
                String colTipo = fila.get(1).toString();
                String conPres = fila.get(2).toString();
                boolean notNull = Boolean.parseBoolean(fila.get(3).toString());
                boolean pk = Boolean.parseBoolean(fila.get(4).toString());

                ddl.append("  ").append(colNombre).append(" ").append(colTipo);
                if (!conPres.isEmpty() && 
                ("VARCHAR".equalsIgnoreCase(colTipo) || 
                 "CHAR".equalsIgnoreCase(colTipo) || 
                 "DECIMAL".equalsIgnoreCase(colTipo))) {
                ddl.append("(").append(conPres).append(")");
            }

            if (notNull) ddl.append(" NOT NULL");
            if (pk) ddl.append(" PRIMARY KEY");

            if (i < data.size() - 1) ddl.append(",");
            ddl.append("\n");
            }
            ddl.append(");");
            tAddl.setText(ddl.toString());

        } else if ("View".equalsIgnoreCase(tipo)) {
            String sqlSelect = tASelect.getText().trim();
            if (sqlSelect.isEmpty()) {
                tAddl.setText("-- Escribe el SELECT para la vista");
            } else {
                tAddl.setText("CREATE VIEW " + nombre + " AS\n" + sqlSelect + ";");
            }
        }
    }

    public void agregarColumna(String nombre, String tipo, String longitud, boolean notNull, boolean pk) {
        mdlCol.addRow(new Object[]{nombre, tipo, longitud, notNull, pk});
        actualizarDDL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombreTV = new javax.swing.JTextField();
        cmbTV = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnGuardarNew = new javax.swing.JButton();
        tAddl = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tASelect = new javax.swing.JTextArea();
        btnRegresar2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPrecision = new javax.swing.JTextField();
        cmbTD = new javax.swing.JComboBox<>();
        txtCN = new javax.swing.JTextField();
        chkNN = new javax.swing.JCheckBox();
        chkPK = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTV = new javax.swing.JTable();
        btnAddC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        txtNombreTV.setBackground(new java.awt.Color(204, 204, 204));
        txtNombreTV.setForeground(new java.awt.Color(0, 0, 0));

        cmbTV.setBackground(new java.awt.Color(255, 255, 255));
        cmbTV.setForeground(new java.awt.Color(0, 0, 0));
        cmbTV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbTVMouseClicked(evt);
            }
        });
        cmbTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTVActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));

        btnGuardarNew.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardarNew.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardarNew.setText("Guardar");
        btnGuardarNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarNewActionPerformed(evt);
            }
        });

        tAddl.setBackground(new java.awt.Color(255, 255, 255));
        tAddl.setColumns(20);
        tAddl.setRows(5);
        tAddl.setEnabled(false);
        tAddl.setFocusable(false);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        tASelect.setColumns(20);
        tASelect.setRows(5);
        jScrollPane1.setViewportView(tASelect);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        btnRegresar2.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar2.setText("Regresar");
        btnRegresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tipo de dato");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Longitud/Precision");

        txtPrecision.setBackground(new java.awt.Color(255, 255, 255));

        cmbTD.setBackground(new java.awt.Color(255, 255, 255));
        cmbTD.setForeground(new java.awt.Color(0, 0, 0));
        cmbTD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtCN.setBackground(new java.awt.Color(255, 255, 255));

        chkNN.setBackground(new java.awt.Color(255, 255, 255));
        chkNN.setForeground(new java.awt.Color(0, 0, 0));
        chkNN.setText("NOT NULL?");
        chkNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNNActionPerformed(evt);
            }
        });

        chkPK.setBackground(new java.awt.Color(255, 255, 255));
        chkPK.setForeground(new java.awt.Color(0, 0, 0));
        chkPK.setText("PRIMARY KEY?");
        chkPK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPKActionPerformed(evt);
            }
        });

        tblTV.setBackground(new java.awt.Color(255, 255, 255));
        tblTV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTV.setEnabled(false);
        jScrollPane2.setViewportView(tblTV);

        btnAddC.setBackground(new java.awt.Color(255, 255, 255));
        btnAddC.setText("Agregar");
        btnAddC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddC)
                .addGap(28, 28, 28))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(chkNN, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(chkPK, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(406, 406, 406))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCN, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbTD, 0, 270, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPrecision, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap()))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCN, txtPrecision});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnAddC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2))
                    .addGap(10, 10, 10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPrecision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(14, 14, 14)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkNN, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkPK))
                    .addContainerGap(395, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreTV, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbTV, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(btnRegresar2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tAddl, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGuardarNew, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(394, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtNombreTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbTV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnRegresar2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(tAddl, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnGuardarNew)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(143, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPKActionPerformed

    private void chkNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkNNActionPerformed

    private void btnAddCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCActionPerformed
        if (txtCN.getText().isEmpty() || cmbTD.getSelectedItem().toString() == null) {
            JOptionPane.showMessageDialog(this, "Debes ingresar nombre y tipo de dato", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        agregarColumna(txtCN.getText(), cmbTD.getSelectedItem().toString(), txtPrecision.getText(), chkNN.isSelected(), chkPK.isSelected());
        txtCN.setText("");
        txtPrecision.setText("");
        chkNN.setSelected(false);
        chkPK.setSelected(false);
    }//GEN-LAST:event_btnAddCActionPerformed

    private void btnRegresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar2ActionPerformed
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresar2ActionPerformed

    private void btnGuardarNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarNewActionPerformed
        String ddl = tAddl.getText().trim();
        if (ddl.isEmpty() || ddl.startsWith("--")) {
            JOptionPane.showMessageDialog(this, "Error", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        TreePath path = log.getJTree().getSelectionPath(); 
        if (path == null || path.getPathCount() < 2) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una conexion", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nombreConexion = path.getPathComponent(1).toString();
        ConexionIB conexion = log.getGestor().getConexion(nombreConexion); 
        if (conexion == null) {
            JOptionPane.showMessageDialog(this, "Error", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            
            if (conexion.getConnection() == null || conexion.getConnection().isClosed()) {
                conexion.estaAbierta();
            }
            Connection con = (Connection) conexion.getConnection();
            try (java.sql.Statement st = con.createStatement()) {
                st.executeUpdate(ddl); 
                JOptionPane.showMessageDialog(this, "Creacion exitosa", "Exito", JOptionPane.INFORMATION_MESSAGE);
            }

            log.actualizarArbol();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error en el create: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
        tAddl.setText("");
    }//GEN-LAST:event_btnGuardarNewActionPerformed

    private void cmbTVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbTVMouseClicked

    }//GEN-LAST:event_cmbTVMouseClicked

    private void cmbTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTVActionPerformed
        if(mdlCol == null){
            return;
        }
        Object selected = cmbTV.getSelectedItem();
        if (selected == null) {
            return;
        }
        if (cmbTV.getSelectedItem().equals("Table")) {
            jLabel1.setText("Nombre de Tabla:");
            jPanel2.setVisible(true);
            jPanel2.setEnabled(true);
            jPanel3.setVisible(false);
            jPanel2.setEnabled(false);
        } else if (cmbTV.getSelectedItem().equals("View")) {
            jLabel1.setText("Nombre de Vista:");
            jPanel2.setVisible(false);
            jPanel2.setEnabled(false);
            jPanel3.setVisible(true);
            jPanel2.setEnabled(true);
        }

        actualizarDDL();
    }//GEN-LAST:event_cmbTVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new createTV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddC;
    private javax.swing.JButton btnGuardarNew;
    private javax.swing.JButton btnRegresar2;
    private javax.swing.JCheckBox chkNN;
    private javax.swing.JCheckBox chkPK;
    private javax.swing.JComboBox<String> cmbTD;
    private javax.swing.JComboBox<String> cmbTV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea tASelect;
    private javax.swing.JTextArea tAddl;
    private javax.swing.JTable tblTV;
    private javax.swing.JTextField txtCN;
    private javax.swing.JTextField txtNombreTV;
    private javax.swing.JTextField txtPrecision;
    // End of variables declaration//GEN-END:variables
}
